on:
  schedule:
    # Thursday at 12am, 6am, 12pm, and 6pm (Eastern Standard Time - EST)
    - cron: |
        0 0,6,12,18 * * 4
    # Friday at 12am, 12:30am, 1am, 1:15am, 1:30am, 6am, 12pm, and 6pm (EST)
    - cron: |
        0 0,6,12,18 * * 5
        30 1,6,12,18 * * 5
        15 1 * * 5
    # Saturday at 6am, 12pm, and 6pm (EST)
    - cron: |
        0 6,12,18 * * 6
    # Sunday at 6am, 12pm, 4pm, 5pm, 5:30pm, 6pm, 6:30pm, 7pm, 7:30pm, 8pm, 8:30pm, 9pm, 9:30pm, 10pm, 10:30pm, 11pm, and 11:30pm (EST)
    - cron: |
        0 6,12 * * 0
        0 16,17,18,19,20,21,22,23 * * 0
    # Monday at 12am, 12:30am, 1am, 1:30am, 6am, 12pm, 6pm, and 11pm (EST)
    - cron: |
        0 0,6,12,18,23 * * 1
        30 1,6 * * 1
    # Tuesday at 12am, 12:30am, 1am, 1:30am, 2am, 6am, 12pm, and 6pm (EST)
    - cron: |
        0 0,6,12,18 * * 2
        30 1,6,14 * * 2
    # Wednesday at 12am, 6am, 12pm, and 6pm (EST)
    - cron: |
        0 0,6,12,18 * * 3
  workflow_dispatch:
  
jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::nflreadr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("app df.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          # git add schedule_test.csv
          git add *
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
