on:
  schedule:
    # Full schedule (active outside March 1–September 1)
    - cron:  '0 0,6,12,18,23 * * 4'  # Thursday
    - cron:  '0 6 * * 4'
    - cron:  '0 12,18 * * 4'
    - cron:  '0 23 * * 4'
    - cron:  '0 0,6,12,18 * * 5'     # Friday
    - cron:  '30 0,6,12,18 * * 5'
    - cron:  '15 1 * * 5'
    - cron:  '0 6,12,18 * * 6'       # Saturday
    - cron:  '0 6 * * 0'             # Sunday
    - cron:  '0 12,16,17,18,19,20,21,22,23 * * 0'
    - cron:  '0 0,1,2,3,4,5,6,7,8,9,10,11,12,18,23 * * 1'  # Monday
    - cron:  '30 1,6 * * 1'
    - cron:  '0 23 * * 1'
    - cron:  '0 0,6,7,8,9,10,11,12,18 * * 2'  # Tuesday
    - cron:  '30 1,6,14 * * 2'
    - cron:  '0 0,6,12,18 * * 3'     # Wednesday

    # Weekly Sunday 9 AM run (active March 1–September 1)
    - cron: '0 9 * * 0'

  workflow_dispatch:

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check if current schedule should run
        run: |
          current_day=$(date +%u)  # 0 = Sunday, 1 = Monday, ..., 6 = Saturday
          current_hour=$(date +%H)
          today=$(date +%m-%d)

          start="03-01"
          end="09-01"

          if [[ "$today" > "$start" && "$today" < "$end" ]]; then
            if [[ "$current_day" -ne 0 || "$current_hour" -ne 9 ]]; then
              echo "Within seasonal range, but not Sunday at 9 AM. Skipping."
              exit 0
            fi
          else
            echo "Outside seasonal range. Proceeding with full schedule."
          fi

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::nflreadr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("DOUG Shiny App Dataframe Code.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
